// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  MatchSettings,
  MatchSide,
} from "./types";


export default __t.row({
  matchId: __t.u64().primaryKey().name("match_id"),
  get settings() {
    return MatchSettings;
  },
  get winner() {
    return MatchSide;
  },
  endedAt: __t.timestamp().name("ended_at"),
  hostName: __t.string().name("host_name"),
  redTeamNames: __t.array(__t.string()).name("red_team_names"),
  blueTeamNames: __t.array(__t.string()).name("blue_team_names"),
});
