// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  HistoryStep,
  CharSnapshot,
} from "./types";


export default __t.row({
  matchId: __t.u64().primaryKey().name("match_id"),
  get steps() {
    return __t.array(HistoryStep);
  },
  get snapshots() {
    return __t.array(CharSnapshot);
  },
});
