// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  MatchSide,
  MatchRole,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  matchId: __t.u64().name("match_id"),
  userId: __t.identity().name("user_id"),
  isReferee: __t.bool().name("is_referee"),
  get side() {
    return MatchSide;
  },
  get role() {
    return MatchRole;
  },
  slotIndex: __t.u8().name("slot_index"),
});
