// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  MatchStatus,
  MatchSettings,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  hostId: __t.identity().name("host_id"),
  get status() {
    return MatchStatus;
  },
  get settings() {
    return MatchSettings;
  },
  startedAt: __t.timestamp().name("started_at"),
  lastActionAt: __t.timestamp().name("last_action_at"),
});
