// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  SynergyValues,
} from "./types";


export default __t.row({
  id: __t.string().primaryKey(),
  source: __t.string(),
  pairTarget: __t.string().name("pair_target"),
  get cost() {
    return SynergyValues;
  },
});
