// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  UserRole,
} from "./types";


export default __t.row({
  id: __t.identity().primaryKey(),
  nickname: __t.string(),
  discordId: __t.option(__t.string()).name("discord_id"),
  online: __t.bool(),
  get role() {
    return UserRole;
  },
  profilePicture: __t.string().name("profile_picture"),
});
